[tool.poetry]
name = "pylater"
version = "0.1.0"
description = ""
authors = ["Damien Mannion <damien@djmannion.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.26.4"
scipy = "^1.12.0"
pymc = "^5.12.0"
sympy = "^1.12"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"
black = "^24.3.0"
mypy = "^1.9.0"
pytest = "^7.4.4"
fawltydeps = "^0.13.3"

[tool.poetry.group.interactive.dependencies]
ipython = "^8.20.0"
pickleshare = "^0.7.5"
matplotlib = "^3.8.2"
pyqt6 = "^6.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
preview = false
skip-source-first-line = false
skip-string-normalization = false
skip-magic-trailing-comma = false

[tool.ruff]
exclude = []
select = [
	"E",  # error
	"F",  # pyflakes
	"UP",  # pyupgrade
	"N",  # pep8-naming
	"ANN",  # flake8-annotations
	"A",  # flake8-builtins
	"PTH",  # flake8-usepathlib
	"B",  # flake8-bugbear
	"Q",  # flake8-quotes
	"ARG",  # flake8-unused-arguments
	"NPY",  # numpy
	"PERF",  # perflint
	"RUF",  # ruff
]
target-version = "py310"
ignore = [
	"ANN101",  # typing self
]

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
# corresponding to --strict
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
extra_checks = true

[[tool.mypy.overrides]]
module = [
	"scipy",
	"scipy.stats",
]
ignore_missing_imports = true
