[project]
name = "pylater"
version = "0.1.0"
description = "A Python library for working with LATER ('Linear Approach to Threshold with Ergodic Rate for Reaction Times') models using Bayesian methods in PyMC."
readme = "README.md"
authors = [
    { name = "Damien Mannion", email = "damien.mannion@unimelb.edu.au" }
]
requires-python = ">=3.12"
license = "MIT"
dependencies = [
    "arviz[netcdf4]>=1.0",
    "matplotlib",
    "numba",
    "numpy",
    "pymc>=6.0.0",
    "scipy",
    "xarray",
]

[project.scripts]
pylater = "pylater:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
    "scipy-stubs>=1.18.1.0",
]

# TASK RUNNER
[tool.poe.executor]
type = "uv"

[tool.poe.tasks.lint]
cmd = "ruff check"
executor = {group = "dev"}

[tool.poe.tasks.typecheck]
cmd = "mypy ."
executor = {group = "dev"}

[tool.poe.tasks.test]
cmd = "pytest --cov --cov-report term-missing"
executor = {group = "dev"}

# MYPY CONFIG
[tool.mypy]
strict = true
warn_unreachable = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
exclude = [
  "docs/",
]

[[tool.mypy.overrides]]
module = [
  "pymc",
  "arviz",
  "pytensor.*",
]
ignore_missing_imports = true

# RUFF CONFIG
[tool.ruff]
exclude = [
  "docs",
  "*.ipynb",
  "tests/"
]
lint.select = [
  "ALL",
]
lint.ignore = [
  "PERF203",  # performance overhead from try/catch in loops
  "I001",  # unsorted imports
  "D",  # docs
  "S311",  # random number generator warning
  "COM812",  # trailing commas
  "E501",  # line length
  "RSE102",  # raise without brackets
  "RET504",  # unnessary return assignment
  "G004",  # logging using f-strings
  "G003",  # logging using +
  "TRY003",  # long exception messages
  "S101",  # ok with assert
  "C901",  # 'too complex'
  "PLR0913",  # too many args in func def
  "PLR0912",  # too many branches
  "S324",  # insecure hash
  "N812",  # lightning as L import
  "S301",  # pickle security
  "PLR0915",  # too many statements
  "DTZ",  # require timezones
  "N80",  # upper case names
  "CPY001",  # copyright
  "RUF018",
  "ANN002", "ANN003",
  "ERA001",
  "UP032",
  "PLR0917",
  "RUF023",
  "RUF022",
]
